services:

  # DEV
  # kino-babilon-backend-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: kino-babilon-backend-dev
  #   ports:
  #     - "8008:8008"
  #   volumes:
  #     - .:/app
  #     - ./kino_babilon_dev.db:/app/kino_babilon.db
  #   env_file:
  #     - .env

  # MASTER
  kino-babilon-backend:
    image: suchencjusz/kino-babilon-backend:latest
    container_name: kino-babilon-backend
    ports:
      - "8008:8008"
    volumes:
      - .:/app
      - ./kino_babilon.db:/app/kino_babilon.db
    env_file:
      - .env