volumes:
  kino-db-volume:
    driver: local


services:

  # DEV
  # kino-babilon-backend-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #
  #   container_name: kino-babilon-backend-dev
  #   restart: unless-stopped
  #   ports:
  #     - "8008:8008"
  #   volumes:
  #     - kino-db-volume:/app/data
  #   env_file:
  #     - .env


  # MASTER
  kino-babilon-backend:
    image: suchencjusz/kino-babilon-backend:latest
    container_name: kino-babilon-backend
    restart: unless-stopped
    ports:
      - "8008:8008"
    volumes:
      - kino-db-volume:/app/data
    env_file:
      - .env


