services:
  kino_babilon_backed:
    container_name: kino_babilon_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./kino_babilon.db:/app/kino_babilon.db
    env_file:
      - .env

  # kino_babilon_backed:
  #   image: 
  #   container_name: kino_babilon_backed
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./:/app
  #     - ./kino_babilon.db:/app/kino_babilon.db
  #   env_file:
  #     - .env