"""Dodanie kolumny archiwalny

Revision ID: a0c59386631d
Revises: a8e6a9891f14
Create Date: 2025-10-21 11:29:23.068931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c59386631d'
down_revision: Union[str, None] = 'a8e6a9891f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seanse', sa.Column('archiwalny', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seanse', 'archiwalny')
    # ### end Alembic commands ###
